# -----------------------------------------------------------------------------
# Project
# -----------------------------------------------------------------------------

sonar.projectKey=FleetOps-Corp_FleetOps-Reports-Service 
sonar.projectName=FleetOps Reports
sonar.projectVersion=1.0.0

# Obligatorio en SonarCloud
sonar.organization=fleetops-corp

# -----------------------------------------------------------------------------
# Sources
# -----------------------------------------------------------------------------

sonar.sources=backend/src
sonar.tests=backend/tests
sonar.sourceEncoding=UTF-8

# -----------------------------------------------------------------------------
# Python
# -----------------------------------------------------------------------------

sonar.python.version=3.13
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.python.bandit.reportPaths=bandit-report.json

# -----------------------------------------------------------------------------
# Exclusions
# -----------------------------------------------------------------------------

sonar.exclusions=\
**/__pycache__/**,\
**/.venv/**,\
**/venv/**,\
**/node_modules/**,\
**/htmlcov/**,\
**/.pytest_cache/**,\
**/.mypy_cache/**,\
**/.ruff_cache/**,\
**/migrations/**,\
**/observability/**,\
**/gateway/**,\
**/minio/**,\
**/docker-compose*.yml

sonar.coverage.exclusions=\
**/tests/**,\
**/*test*.py,\
**/__init__.py

# -----------------------------------------------------------------------------
# Analysis
# -----------------------------------------------------------------------------

sonar.verbose=false