"""KPI domain model.

SAD Traceability: captures analytical indicators and operational metrics
generated by FleetOps Reports according to SAD sections 3, 6 and 10.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime

from fleetops_reports.domain.value_objects.metric import Metric


@dataclass(frozen=True)
class KPI:
    name: str
    metric: Metric
    source: str
    calculated_at: datetime

    @classmethod
    def create_now(cls, name: str, metric: Metric, source: str) -> KPI:
        return cls(name=name, metric=metric, source=source, calculated_at=datetime.now(UTC))

